name: dashcore
description: "DashCore - Open-source OBD2 dashboard app for real-time car data and diagnostics."
homepage: https://github.com/iUnreallx/DashCore
version: 1.0.2+4

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  provider: ^6.1.5+1
  flutter_blue_classic: ^0.0.9
  permission_handler: ^12.0.1
  device_info_plus: ^12.4.0
  flutter_native_splash: ^2.4.7
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  model_viewer_plus: ^1.9.3
  share_plus: ^10.1.3
  maplibre_gl: ^0.26.2
  geolocator: ^13.0.1
  location: ^7.0.1
  nowplaying: ^3.0.3
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.5
  path_provider: ^2.1.3
  http: ^1.2.1
  supabase_flutter: ^2.17.2
  url_launcher: ^6.3.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/svg/dashboard/
    - assets/images/svg/bottomBar/
    - assets/images/png/
    - assets/images/preview_store/
    - assets/images/gifstore/
    - assets/icons/
    - assets/icon/
    - assets/models/
    - assets/world_map.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Logoapp.png"
  adaptive_icon_background: "#080B10"
  adaptive_icon_foreground: "assets/icon/Logoapp.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/icons/app_ico.png"

  windows:
    generate: true
    image_path: "assets/icons/app_ico.png"

flutter_native_splash:
  color: "#080B10"
  image: assets/icon/Logoapp.png
  color_dark: "#080B10"
  image_dark: assets/icon/Logoapp.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#080B10"
    image: assets/icons/splash_logo.png
    icon_background_color: "#080B10"
