// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozi4bY_RDwcIAAD3YvTG6_QO_QOuse-0',
    appId: '1:881931808993:web:8fe30b321fdf12b26707a0',
    messagingSenderId: '881931808993',
    projectId: 'dashcore-4535d',
    authDomain: 'dashcore-4535d.firebaseapp.com',
    storageBucket: 'dashcore-4535d.firebasestorage.app',
    measurementId: 'G-X838GGXZD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfOq-TRm3DfCy_Z3QbJSD5egAIlPmZ9o',
    appId: '1:881931808993:android:397bc51eccb9f91a6707a0',
    messagingSenderId: '881931808993',
    projectId: 'dashcore-4535d',
    storageBucket: 'dashcore-4535d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZOmVJNVIcqcBmyKZ4GimUIxT6pLk1xc',
    appId: '1:881931808993:ios:b412b063880361496707a0',
    messagingSenderId: '881931808993',
    projectId: 'dashcore-4535d',
    storageBucket: 'dashcore-4535d.firebasestorage.app',
    iosBundleId: 'com.dashcore.app',
  );
}
